name: CI

on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bob checks
        run: |
          docker run --rm \
          --workdir "/project" -v "${PWD}:/project" \
          magnetcoop/bob:2e3b8bc \
          sh -c "all-checks.sh"
